spring.application.name=ecommerce

# Server
server.port=8000

# H2 file-based DB (dev)
spring.datasource.url=jdbc:h2:file:./ecommerce
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI / Swagger
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operations-sorter=alpha
